version: '3.8'

services:
  # --- Baza danych PostgreSQL ---
  museum-db:
    image: postgres:15-alpine
    container_name: museum_postgres
    restart: always
    environment:
      POSTGRES_DB: museum_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # --- Panel graficzny pgAdmin (do podglÄ…du bazy) ---
  pgadmin:
    image: dpage/pgadmin4
    container_name: museum_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - museum-db

volumes:
  postgres_data: